kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    image: kindest/node:v1.19.3
    # add a mount from /path/to/my/files on the host to /files on the node
    extraMounts:
      - hostPath: /scratch
        containerPath: /scratch
  - role: worker
    image: kindest/node:v1.19.3
    extraMounts:
      - hostPath: /scratch/worker0
        containerPath: /scratch
  - role: worker
    image: kindest/node:v1.19.3
    extraMounts:
      - hostPath: /scratch/worker1
        containerPath: /scratch
